-- MySQL Script generated by MySQL Workbench
-- 04/02/16 16:49:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema srecreig_base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema srecreig_base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `srecreig_base` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `srecreig_base` ;

-- -----------------------------------------------------
-- Table `srecreig_base`.`Connexion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`Connexion` (
  `id` VARCHAR(70) NOT NULL,
  `pass` VARCHAR(64)NULL,
  `profil` VARCHAR(10) NOT NULL DEFAULT 'read',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `connexion` (`id`, `pass`, `profil`) VALUES
('madame.lecture', '62db9e0f40b319a7e47788c541dacea3', 'read'),
('monsieur.ecriture', '9c8e4f0f59c5bba8a1557a233704641a', 'write'),
('rachid.lebrache', '9df3b01c60df20d13843841ff0d4482c', 'super');

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`NAF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`NAF` (
  `codeNAF` INT NOT NULL,
  `libelleNAF` INT NULL,
  PRIMARY KEY (`codeNAF`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`Entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`Entreprise` (
  `nomEntreprise` VARCHAR(70) NOT NULL,
  `groupe` VARCHAR(70) NULL,
  `adresse` VARCHAR(70) NULL,
  `complementAdresse` VARCHAR(70) NULL,
  `codePostal` VARCHAR(5) NULL,
  `ville` VARCHAR(100) NULL,
  `pays` VARCHAR(50) NULL,
  `typeContact` VARCHAR(70) NULL,
  `origine` VARCHAR(70) NULL,
  `numeroSIRET` VARCHAR(70) NULL,
  `NAF_codeNAF` INT NULL,
  `partenariatOfficiel` VARCHAR(3) NULL DEFAULT 'NON',
  `taille` VARCHAR(20) NULL,
  `alias` TEXT(500) NULL,
  `commentairesEntreprise` LONGTEXT NULL,
  PRIMARY KEY (`nomEntreprise`),
  INDEX `fk_Entreprise_Naf_idx` (`NAF_codeNAF` ASC),
  CONSTRAINT `fk_Entreprise_NAF`
    FOREIGN KEY (`NAF_codeNAF`)
    REFERENCES `srecreig_base`.`NAF` (`codeNAF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`CoordonneesPersonne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`CoordonneesPersonne` (
  `idCoordonneesPersonne` INT NOT NULL AUTO_INCREMENT,
  `civilite` VARCHAR(20) NULL,
  `nom` VARCHAR(20) NULL,
  `prenom` VARCHAR(20) NULL,
  `fonction` VARCHAR(100) NULL,
  `telephoneFixe` VARCHAR(20) NULL,
  `telephoneMobile` VARCHAR(20) NULL,
  `mail` VARCHAR(70) NULL,
  `commentaires` LONGTEXT NULL,
  PRIMARY KEY (`idCoordonneesPersonne`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`Conference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`Conference` (
  `idConference` INT NOT NULL AUTO_INCREMENT,
  `Entreprise_nomEntreprise` VARCHAR(40) NOT NULL,
  `typeConference` VARCHAR(20) NULL,
  `dateConference` DATE NULL,
  `heureDebut` TIME NULL,
  `heureFin` TIME NULL,
  `lieuConference` VARCHAR(45) NULL,
  `themeConference` VARCHAR(100) NULL,
  PRIMARY KEY (`idConference`, `Entreprise_nomEntreprise`),
  INDEX `fk_Conference_Entreprise1_idx` (`Entreprise_nomEntreprise` ASC),
  CONSTRAINT `fk_Conference_Entreprise`
    FOREIGN KEY (`Entreprise_nomEntreprise`)
    REFERENCES `srecreig_base`.`Entreprise` (`nomEntreprise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`CycleFormation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`CycleFormation` (
  `idCycleFormation` INT NOT NULL,
  `cycle` VARCHAR(70) NOT NULL,
  `mention` VARCHAR(70) NULL,
  `specialite` VARCHAR(70) NULL,
  PRIMARY KEY (`idCycleFormation`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`ForumSG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`ForumSG` (
  `Entreprise_nomEntreprise` VARCHAR(70) NOT NULL,
  `anneeDeParticipation` YEAR(4) NOT NULL,
  `questionnaireDeSatisfaction` VARCHAR(100) NULL,
  `commentairesForum` LONGTEXT NULL,
  PRIMARY KEY (`Entreprise_nomEntreprise`, `anneeDeParticipation`),
  INDEX `fk_forumSG_Entreprise1_idx` (`Entreprise_nomEntreprise` ASC),
  CONSTRAINT `fk_ForumSG_Entreprise`
    FOREIGN KEY (`Entreprise_nomEntreprise`)
    REFERENCES `srecreig_base`.`Entreprise` (`nomEntreprise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`AtelierRH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`AtelierRH` (
  `idAtelierRH` INT NOT NULL AUTO_INCREMENT,
  `Entreprise_nomEntreprise` VARCHAR(70) NOT NULL,
  `dateAtelier` DATE NULL,
  `creneauAtelier` VARCHAR(20) NULL,
  INDEX `fk_atelierRh_Entreprise1_idx` (`Entreprise_nomEntreprise` ASC),
  PRIMARY KEY (`idAtelierRH`),
  CONSTRAINT `fk_AtelierRH_Entreprise`
    FOREIGN KEY (`Entreprise_nomEntreprise`)
    REFERENCES `srecreig_base`.`Entreprise` (`nomEntreprise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`Alternance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`Alternance` (
  `Entreprise_nomEntreprise` VARCHAR(70) NOT NULL,
  `formationAlternance` VARCHAR(5) NULL,
  `anneeEntree` INT NULL,
  `typeContrat` VARCHAR(70) NULL,
  `CoordonneesPersonne_alternant` INT NOT NULL,
  `CoordonneesPersonne_maitre` INT NULL,
  `CoordonneesPersonne_RH` INT NULL,
  `dateRVPreparation` DATE NULL,
  `dateRVSimulation` DATE NULL,
  `dateDebutContrat` YEAR(4) NULL,
  `dateFinContrat` YEAR(4) NULL,
  `dateRuptureContrat` DATE NULL,
  `dateEnvoiFLAuCFA` DATE NULL,
  `docAAttacher` VARCHAR(200) NULL,
  PRIMARY KEY (`CoordonneesPersonne_alternant`),
  INDEX `fk_apprentissage_Entreprise1_idx` (`Entreprise_nomEntreprise` ASC),
  INDEX `fk_apprentissage_coordoneesPersonneMaitre_idx` (`CoordonneesPersonne_RH` ASC),
  CONSTRAINT `fk_Alternance_Entreprise`
    FOREIGN KEY (`Entreprise_nomEntreprise`)
    REFERENCES `srecreig_base`.`Entreprise` (`nomEntreprise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Alternance_CoordonneesPersonneAlternant`
    FOREIGN KEY (`CoordonneesPersonne_alternant`)
    REFERENCES `srecreig_base`.`CoordonneesPersonne` (`idCoordonneesPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Alternance_CoordonneesPersonneMaitre`
    FOREIGN KEY (`CoordonneesPersonne_RH`)
    REFERENCES `srecreig_base`.`CoordonneesPersonne` (`idCoordonneesPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Alternance_CoordonneesPersonneRH`
    FOREIGN KEY (`CoordonneesPersonne_RH`)
    REFERENCES `srecreig_base`.`CoordonneesPersonne` (`idCoordonneesPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`a_AtelierRH_CoordonneesPersonne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`a_AtelierRH_CoordonneesPersonne` (
  `AtelierRH_id` INT NOT NULL,
  `CoordonneesPersonne_id` INT NOT NULL,
  PRIMARY KEY (`AtelierRH_id`, `CoordonneesPersonne_id`),
  INDEX `fk_ContactAtelierRh_atelierRh1_idx` (`AtelierRH_id` ASC),
  CONSTRAINT `fk_a-AtelierRH-CoordonneesPersonne_CoordonneesPersonne`
    FOREIGN KEY (`CoordonneesPersonne_id`)
    REFERENCES `srecreig_base`.`CoordonneesPersonne` (`idCoordonneesPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a-AtelierRH-CoordonneesPersonne_AtelierRH`
    FOREIGN KEY (`AtelierRH_id`)
    REFERENCES `srecreig_base`.`AtelierRH` (`idAtelierRH`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`a_Conference_CoordonneesPersonne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`a_Conference_CoordonneesPersonne` (
  `Conference_id` INT NOT NULL,
  `CoordonneesPersonne_id` INT NOT NULL,
  PRIMARY KEY (`Conference_id`, `CoordonneesPersonne_id`),
  INDEX `fk_conferencier_coordoneesPersonne1_idx` (`CoordonneesPersonne_id` ASC),
  CONSTRAINT `fk_a-Conference-CoordonneesPersonne_Conference`
    FOREIGN KEY (`Conference_id`)
    REFERENCES `srecreig_base`.`Conference` (`idConference`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a-Conference-CoordonneesPersonne_CoordonneesPersonne`
    FOREIGN KEY (`CoordonneesPersonne_id`)
    REFERENCES `srecreig_base`.`CoordonneesPersonne` (`idCoordonneesPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`Action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`Action` (
  `idAction` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAction`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`a_Entreprise_Action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`a_Entreprise_Action` (
  `Entreprise_nomEntreprise` VARCHAR(70) NOT NULL,
  `Action_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Entreprise_nomEntreprise`, `Action_id`),
  INDEX `fk_a_actEnt_Entreprise_idx` (`Entreprise_nomEntreprise` ASC),
  CONSTRAINT `fk_a-Entreprise-Action_Action`
    FOREIGN KEY (`Action_id`)
    REFERENCES `srecreig_base`.`Action` (`idAction`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a-Entreprise-Action_Entreprise`
    FOREIGN KEY (`Entreprise_nomEntreprise`)
    REFERENCES `srecreig_base`.`Entreprise` (`nomEntreprise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`a_Entreprise_CycleFormation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`a_Entreprise_CycleFormation` (
  `Entreprise_nomEntreprise` VARCHAR(70) NOT NULL,
  `CycleFormation_id` INT NOT NULL,
  PRIMARY KEY (`Entreprise_nomEntreprise`, `CycleFormation_id`),
  INDEX `fk_acfen_En_idx` (`Entreprise_nomEntreprise` ASC),
  CONSTRAINT `fk_a-Entreprise-CycleFormation_CycleFormation`
    FOREIGN KEY (`CycleFormation_id`)
    REFERENCES `srecreig_base`.`CycleFormation` (`idCycleFormation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a-Entreprise-CycleFormation_Entreprise`
    FOREIGN KEY (`Entreprise_nomEntreprise`)
    REFERENCES `srecreig_base`.`Entreprise` (`nomEntreprise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`TaxeApprentissage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`TaxeApprentissage` (
  `idTA` INT NOT NULL AUTO_INCREMENT,
  `Entreprise_nomEntreprise` VARCHAR(70) NOT NULL,
  `anneeDeVersement` YEAR(4) NULL,
  `montantPromesseVersement` INT NULL,
  `montantVerse` INT NULL,
  `OCTA` VARCHAR(50) NULL,
  `dateEnregistrement` DATE NULL,
  `dateDerniereModification` DATE NULL,
  `modePaiement` VARCHAR(10) NULL,
  `versementVia` VARCHAR(50) NULL,
  `dateTransmissionChequeAC` DATE NULL,
  `rapprochementAC` DATE NULL,
  `commentairesTaxe` LONGTEXT NULL,
  PRIMARY KEY (`idTA`),
  INDEX `fk_TA_Entreprise_idx` (`Entreprise_nomEntreprise` ASC),
  CONSTRAINT `fk_TA_Entreprise`
    FOREIGN KEY (`Entreprise_nomEntreprise`)
    REFERENCES `srecreig_base`.`Entreprise` (`nomEntreprise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`a_TaxeApprentissage_CycleFormation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`a_TaxeApprentissage_CycleFormation` (
  `TaxeApprentissage_id` INT NOT NULL,
  `CycleFormation_id` INT NOT NULL,
  `categorie` VARCHAR(1) NOT NULL,
  `montant` INT NOT NULL,
  PRIMARY KEY (`TaxeApprentissage_id`, `CycleFormation_id`, `categorie`, `montant`),
  INDEX `fk_acfta_TA_idx` (`TaxeApprentissage_id` ASC),
  CONSTRAINT `fk_a-TaxeApprentissage-CycleFormation_CycleFormation`
    FOREIGN KEY (`CycleFormation_id`)
    REFERENCES `srecreig_base`.`CycleFormation` (`idCycleFormation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a-TaxeApprentissage-CycleFormation_TaxeApprentissage`
    FOREIGN KEY (`TaxeApprentissage_id`)
    REFERENCES `srecreig_base`.`TaxeApprentissage` (`idTA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `srecreig_base`.`a_Entreprise_CoordonneesPersonne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `srecreig_base`.`a_Entreprise_CoordonneesPersonne` (
  `Entreprise_nomEntreprise` VARCHAR(70) NOT NULL,
  `CoordonneesPersonne_id` INT NOT NULL,
  `type` VARCHAR(10) NULL,
  PRIMARY KEY (`Entreprise_nomEntreprise`, `CoordonneesPersonne_id`),
  INDEX `fk_conferencier_coordoneesPersonne1_idx` (`CoordonneesPersonne_id` ASC),
  CONSTRAINT `fk_a-Entreprise-CoordonneesPersonne_Entreprise`
    FOREIGN KEY (`Entreprise_nomEntreprise`)
    REFERENCES `srecreig_base`.`Entreprise` (`nomEntreprise`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_a-Entreprise-CoordonneesPersonne_CoordonneesPersonne`
    FOREIGN KEY (`CoordonneesPersonne_id`)
    REFERENCES `srecreig_base`.`CoordonneesPersonne` (`idCoordonneesPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE IF NOT EXISTS `contact_ta_import` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nomEntreprise` varchar(40) DEFAULT NULL,
  `nom` varchar(20) DEFAULT NULL,
  `prenom` varchar(20) DEFAULT NULL,
  `civilite` varchar(20) DEFAULT NULL,
  `fonction` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=28 ;

--
-- Contenu de la table `contact_ta_import`
--

INSERT INTO `contact_ta_import` (`id`, `nomEntreprise`, `nom`, `prenom`, `civilite`, `fonction`) VALUES
(1, 'ADP', 'COINTREL', 'Marie-Christine', 'Madame', 'Directeur services informatiques'),
(2, 'ALCATEL LUCENT', 'EL SHESHTAWY', 'Nagy', 'Monsieur', 'Chargé RH'),
(3, 'ALSTOM', 'PAILLY', 'Vanessa', 'Madame', 'Chargée RH Relations Ecoles'),
(4, 'ANGST PFISTER SA', 'ROINEAU', 'Valérie', 'Madame', 'Service des Ressources Humaines'),
(5, 'AXIMUM', 'MOYSON', 'Isabelle', 'Madame', 'DRH adjoint pôle Travaux&Services'),
(6, 'B2T', 'TEPLIER', 'Bruno', 'Monsieur', 'GERANT'),
(7, 'GIAT INDUSTRIES', 'BURTIN', 'Philippe', 'Monsieur', 'Président'),
(8, 'LINK BY NET', 'LAURENDON', 'Cédric', 'Monsieur', 'Responsable recrutement'),
(9, 'MACIF ILE DE FRANCE', 'LESPINASSE', 'Jerome', 'Monsieur', 'Direction des Ressources Humaines'),
(10, 'MEDIAPOST', 'GONNET', 'Claire', 'Madame', 'Chargée de Développement RH Pôle Emploi et Di'),
(11, 'SNCF', 'MARCOS', 'Nicolas', 'Monsieur', 'Chef de projet expert'),
(12, 'SOCIETE GENERALE', 'MOLINA CHANG', 'Violeta', 'Madame', 'Campus Manager - Universités'),
(13, 'SOFTEAM', 'BUGGEAI', NULL, 'Madame', NULL),
(14, 'SOPRA  STERIA', 'LOSSON', 'Fabrice', 'Monsieur', 'Directeur du recrutement de Sopra Group'),
(15, 'STORENGY', 'MERLHE BONNARD', 'Amélie Magali', 'Madame', 'Chargée RH'),
(16, 'ACCENTURE', 'REAL', 'Florence', 'Madame', 'Responsable Relations Ecoles et Universités'),
(17, 'CAPGEMINI', 'PLENIER', 'Geraldine', 'Madame', 'Directrice Resp Sociale et Environnementale'),
(18, 'CS COMMUNICATION & SYSTEMES', 'LOUW', 'Marine', 'Madame', 'Chef de projets RH'),
(19, 'ENGIE', 'ROZOT', 'René', 'Monsieur', 'Directeur Attraction des Talents - Marque emp'),
(20, 'ENTREPOSE PROJETS', 'CARO', 'Alexandre', 'Monsieur', NULL),
(21, 'ERDF', 'CHEREL', 'Daniel', 'Monsieur', 'Chef du Développement RH Compétences & Divers'),
(22, 'GRDF', 'BARRE', 'Isabelle', 'Madame', 'Responsable Formation – Apprentissage DRHT'),
(23, 'ILEX', 'LAGREZE', 'Rene', 'Monsieur', 'Directeur Général'),
(24, 'LA BANQUE POSTALE  ASSET MANAGEMENT', 'BENCHIMOL', 'Elodie', 'Madame', 'Chargée de Gestion RH'),
(25, 'LARS SA', 'MAITRE', NULL, 'Madame', NULL),
(26, 'RANDSTAD', 'SOMME', 'Patricia', 'Madame', 'Responsable Grands Comptes'),
(27, 'RODOR SA', 'BOIVIN', 'Dorde', 'Monsieur', 'Direction des Ressources Humaines');

CREATE TABLE IF NOT EXISTS `contact_ta2014` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nomEntreprise` varchar(40) DEFAULT NULL,
  `nom` varchar(20) DEFAULT NULL,
  `prenom` varchar(20) DEFAULT NULL,
  `civilite` varchar(20) DEFAULT NULL,
  `fonction` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `contact_ta2015` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nomEntreprise` varchar(40) DEFAULT NULL,
  `nom` varchar(20) DEFAULT NULL,
  `prenom` varchar(20) DEFAULT NULL,
  `civilite` varchar(20) DEFAULT NULL,
  `fonction` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

