INSERT INTO `CoordonneesPersonne`(`civilite`, `nom`, `prenom`, `fonction`, `telephoneFixe`, `telephoneMobile`, `mail`, `commentaires`, `type`) VALUES ("Monsieur","Abdoul Azid","Ashfack","Chef de projet","0000000000","0000000000","abdoulazid.ashfack@gmail.com","Un petit commentaire pour ashfack","Primaire");
INSERT INTO `CoordonneesPersonne`(`civilite`, `nom`, `prenom`, `fonction`, `telephoneFixe`, `telephoneMobile`, `mail`, `commentaires`, `type`) VALUES ("Monsieur","Bouanaoui","Brahim","Developpeur","0000000000","0000000000","b.bouanaoui@gmail.com","Un petit commentaire pour brahim","Secondaire");
INSERT INTO `CoordonneesPersonne`(`civilite`, `nom`, `prenom`, `fonction`, `telephoneFixe`, `telephoneMobile`, `mail`, `commentaires`, `type`) VALUES ("Monsieur","Dkhissi","Salah","Analyste fonctionnel","0000000000","0000000000","dkhssi.salah@gmail.com","Un petit commentaire pour salah","TA");
INSERT INTO `CoordonneesPersonne`(`civilite`, `nom`, `prenom`, `fonction`, `telephoneFixe`, `telephoneMobile`, `mail`, `commentaires`, `type`) VALUES ("Madame","Joundi","Sahar","Responsable BDD","0000000000","0000000000","joundi.sahar@gmail.com","Un petit commentaire pour sahar","Primaire");
INSERT INTO `CoordonneesPersonne`(`civilite`, `nom`, `prenom`, `fonction`, `telephoneFixe`, `telephoneMobile`, `mail`, `commentaires`, `type`) VALUES ("Monsieur","Kacel","Nacim","Developpeur","0000000000","0000000000","nacim.kacel@gmail.com","Un petit commentaire pour nacim","Secondaire");
INSERT INTO `CoordonneesPersonne`(`civilite`, `nom`, `prenom`, `fonction`, `telephoneFixe`, `telephoneMobile`, `mail`, `commentaires`, `type`) VALUES ("Monsieur","Zgoda","Rafal","Developpeur et Responsable BDD","0000000000","0000000000","zgoda.rafal@gmail.com","Un petit commentaire pour rafal","TA");
INSERT INTO `CoordonneesPersonne`(`civilite`, `nom`, `prenom`, `fonction`, `telephoneFixe`, `telephoneMobile`, `mail`, `commentaires`) VALUES ("Monsieur","Boudjraf","Moustapha","Developpeur","0000000000","0000000000","boudjraf@gmail.com","Un petit commentaire pour moustapha l'alternant de CGP SRE");
INSERT INTO `CoordonneesPersonne`(`civilite`, `nom`, `prenom`, `fonction`, `telephoneFixe`, `telephoneMobile`, `mail`, `commentaires`) VALUES ("Monsieur","Alaoui","zoubair","Developpeur","0000000000","0000000000","alaoui@gmail.com","Un petit commentaire pour moustapha l'alternant de CGP SRE");
INSERT INTO `CoordonneesPersonne`(`civilite`, `nom`, `prenom`, `fonction`, `telephoneFixe`, `telephoneMobile`, `mail`, `commentaires`) VALUES ("Monsieur","Alternant","sonPrenom","Developpeur","0000000000","0000000000","alternant@gmail.com","Un petit commentaire pour l'alternant de CGP SRE 2");
INSERT INTO `Entreprise`(`nomEntreprise`, `groupe`, `adresse`, `complementAdresse`, `codePostal`, `ville`, `pays`, `CoordonneesPersonne_primaire`, `CoordonneesPersonne_secondaire`, `CoordonneesPersonne_TA`,`typeContact`, `partenariatOfficiel`, `taille`, `commentaires`) VALUES ("CGP SRE","groupe 3","99 avenue jean baptiste clement","Universite paris 13",93430,"Villetaneuse","France",1,2,3,"Entreprise","OUI","petite","Un commentaire pour l'entreprise cgp sre");
INSERT INTO `Entreprise`(`nomEntreprise`, `groupe`, `adresse`, `complementAdresse`, `codePostal`, `ville`, `pays`, `CoordonneesPersonne_primaire`, `CoordonneesPersonne_secondaire`, `CoordonneesPersonne_TA`,`typeContact`, `partenariatOfficiel`, `taille`, `commentaires`) VALUES ("CGP SRE 2","groupe 3","99 avenue jean baptiste clement","Universite paris 13",93430,"Villetaneuse","France",4,5,6,"Entreprise","OUI","petite","Un commentaire pour l'entreprise cgp sre 2");
INSERT INTO `Alternance`(`Entreprise_nomEntreprise`, `formationAlternance`, `anneEntree`, `typeContrat`, `CoordonneesPersonne_alternant`, `CoordonneesPersonne_maitre`, `CoordonneesPersonne_RH`, `dateRVPreparation`, `dateRVSimulation`, `dateDebutContrat`, `dateFinContrat`, `commentaires`) VALUES ("CGP SRE","AIR",2016,"apprentissage",7,2,3,"01/01/2016","01/02/2016","01/03/2016","01/07/2017","Bienvenue moustapha chez CGP SRE");
INSERT INTO `Alternance`(`Entreprise_nomEntreprise`, `formationAlternance`, `anneEntree`, `typeContrat`, `CoordonneesPersonne_alternant`, `CoordonneesPersonne_maitre`, `CoordonneesPersonne_RH`, `dateRVPreparation`, `dateRVSimulation`, `dateDebutContrat`, `dateFinContrat`, `commentaires`) VALUES ("CGP SRE","AIR",2016,"apprentissage",8,2,3,"01/02/2016","01/03/2016","01/04/2016","01/07/2018","Bienvenue zoubair chez CGP SRE");
INSERT INTO `Alternance` ( `Entreprise_nomEntreprise` , `formationAlternance` , `anneEntree` , `typeContrat` , `CoordonneesPersonne_alternant` , `CoordonneesPersonne_maitre` , `CoordonneesPersonne_RH` , `dateRVPreparation` , `dateRVSimulation` , `dateDebutContrat` , `dateFinContrat` , `commentaires` ) VALUES ("CGP SRE 2", "AIR", 2016, "apprentissage", 9, 2, 3, "01/02/2016", "01/03/2016", "01/04/2016", "01/07/2018", "Bienvenue à l'alternant chez CGP SRE 2")
